---
deployment:
  tasks:
    - export DEPLOYPATH=/home/jeffross/resume-gql.jeff-rossi.com
    - /bin/npm i
    - /bin/npm run build
    - /bin/cp -r dist/* $DEPLOYPATH
    - /bin/cp ormconfig.js $DEPLOYPATH
    - /bin/rm -rf node_modules
    - /bin/rm -rf dist/*