---
deployment:
  tasks:
    - export DEPLOYPATH=/home/jeffross/resume-gql.jeff-rossi.com
    - /bin/cp -r * $DEPLOYPATH
    - /bin/cd $DEPLOYPATH
    - /bin/npm i
    - /bin/npm run build
    - /bin/npm run start